# Настройки Swift Format

# Указывает версию Swift для форматирования
--swiftversion 6.0

# Настройки отступов и пробелов
--indent 4                    # Базовый отступ - 4 пробела
--indentcase true            # Отступы для case в switch
--tabwidth 4                 # Ширина табуляции - 4 пробела
--trimwhitespace always      # Удаление лишних пробелов
--indentstrings true         # Отступы в многострочных строках
--smarttabs enabled          # "Умные" отступы
--xcodeindentation enabled   # Совместимость с Xcode

# Настройки переноса строк
--maxwidth 200               # Максимальная длина строки
#--wraparguments before-first # Перенос аргументов
#--wrapparameters after-first # Перенос параметров
#--wrapconditions before-first # Перенос условий

# Настройки форматирования кода
#--allman false               # Стиль скобок не Allman
--closingparen same-line     # Закрывающая скобка на той же строке
--commas always              # Запятые всегда
#--semicolons never           # Без точек с запятой

# Пробелы в операторах
--operatorfunc spaced        # Пробелы вокруг операторов
--ranges spaced              # Пробелы в диапазонах

# Организация кода
--importgrouping alphabetized # Сортировка импортов
--header strip               # Удаление заголовков файлов

# MARK комментарии
#--markextensions always      # MARK для расширений
