# Основные правила
disabled_rules:
  - trailing_comma  # Отключаем запятые в конце для последнего элемента
  - function_body_length  # Отключаем ограничение на длину тела функции
  - opening_brace

opt_in_rules:
  - empty_count  # Использовать isEmpty вместо count == 0
  - missing_docs  # Требовать документацию для публичных деклараций
  - closure_spacing  # Проверять отступы в замыканиях
  - colon  # Проверять пробелы около двоеточия
  - comma  # Проверять пробелы около запятых
#  - opening_brace  # Проверять положение открывающей скобки
  - control_statement  # Проверять форматирование управляющих конструкций

# Настройки длины
line_length:
  warning: 140  # Предупреждение при превышении
  error: 160    # Ошибка при превышении
  
# Настройки функций
function_parameter_count:
  warning: 5    # Предупреждение при большом количестве параметров
  error: 7      # Ошибка при слишком большом количестве параметров

# Настройки файлов
file_length:
  warning: 400  # Предупреждение при большой длине файла
  error: 1000   # Ошибка при слишком большой длине файла
