# Отключаем правила, которые нам не нужны
disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
  - trailing_comma

# Включаем дополнительные правила
opt_in_rules:
  - empty_count
  - missing_docs

# Настраиваем параметры правил
line_length:
  warning: 140
  error: 200
